version: 0.2
os: linux
files:
  - source: /out.js
    destination: /out.js
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop-app.sh
      timeout: 300
      runas: root