version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: latest
  
  pre_build:
    commands:
      - echo "Installing npm packages"
      - npm install
  
  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "Build finished"

artifacts:
  files:
    - out.js
    - appspec.hieudt37-uat.yml
    - appspec.hieudt37-jenkins.yml
    - appspec.yml
    - scripts/**/*
  discard-paths: no
